baseURL = "http://example.org/"
languageCode = "en-us"
title = "ux & visual design daily logging at NYPL"
theme = "blankblank"
[permalinks]
  post = "/:year/:month/:title/"
[params]
  author = "Ricardo Galvez"
